#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw "Nginx HTTP"
echo "Hello world!" | sudo tee /var/www/html/index.html

#testing nginx
sudo nginx -t

sudo service nginx restart
